name: credora
description: A Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  go_router: ^14.6.0
  http: ^1.2.2
  image_picker: ^1.1.2
  geolocator: ^11.0.0
  intl: ^0.19.0
  